version: "3"

services:
  api:
    image: dmbuddy_api:latest
    build: 
      context: ./config
      dockerfile: api.Dockerfile
    working_dir: /var/api
    env_file: ./config/api.env
    container_name: api
    networks:
      - app_net
    expose:
      - "8000"
    volumes:
      - ./src/api:/var/api/
    command: ["gunicorn", "app:create_app()", "-c/var/gunicorn.conf.py"]
    ports:
      - "8000:8000"
    #DEBUG CONTAINER
    # stdin_open: true # docker run -i
    # tty: true # docker run -t
    # command: ["ash"]
  app:
    image: dmbuddy:latest
    environment:
      - DEBUG=True
    build: 
      context: ./config
      dockerfile: app.Dockerfile
    working_dir: /var/app
    env_file: ./config/app.env
    container_name: app
    expose:
      - "3000"
    ports:
      - "3000:3000"
    networks:
      - app_net
    volumes:
      - ./src/app:/var/app
    command: ["gunicorn", "app:app", "-c/var/gunicorn.conf.py"]
  server:
    image: nginx
    container_name: server
    networks:
      - app_net
    volumes:
      - ./src/app/static:/srv/static
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
    #DEBUG CONTAINER
    command: [nginx-debug, '-g', 'daemon off;']

networks:
  app_net:

